const crypto = require('crypto');
const request = require('request-promise-native');

/**
 * Hashes a string. Uses as the ?state= query parameter to prevent CSRF forgery during OAuth exchange
 * @param input String input string
 * @returns {string} output hashed string
 */
const hash = input => new Buffer(crypto.createHash('sha256').update(input).digest('hex')).toString('base64');

/**
 * Retrieves the OAuth access token given the unique code generated by nest after the user has validated their permissions.
 * @param code String Nest code retrieved from the Authorization URL redirect
 * @returns {Promise<any>}
 */
const getAccessToken = async code => JSON.parse(await request.post(`https://api.home.nest.com/oauth2/access_token?client_id=${process.env.NEST_CLIENT_ID}&client_secret=${process.env.NEST_CLIENT_SECRET}&code=${code}&grant_type=authorization_code`));

module.exports = {
    hash,
    getAccessToken
};
